[package]
name = "multi_currency"
version = "0.1.0"
authors = ["Martin Habovštiak <martin.habovstiak@gmail.com>"]

[dependencies]
csv = "1"
chrono = "0.4.2"
serde = "1"
serde_derive = "1"
toml = "0.4.6"
